### ISSUE TITLE
Composer install failed on Windows 10

### ISSUE THREAD

**Issue by dinhngocvuong** [Silvanite/novatoolpermissions#1]
<img src="https://image.prntscr.com/image/TPrZr_NQTZ65qgQtpCViIw.png">

**Comment by m2de** [comment]
Hi. Thanks for the report. Please can you try a capital S in Silvanite? I will amend read me if that resolves the issue. Many thanks.

**Comment by dinhngocvuong** [comment]
Please check again, it shows "Package not found"
<img src="https://image.prntscr.com/image/u0bu-uuoRCicxrVKhjRxZA.png">

**Comment by m2de** [comment]
Not a big windows user myself so not sure why this is happening. I will need to dig out my windows laptop to debug, shall post an update as soon as I have resolved this.

**Comment by dinhngocvuong** [comment]
This is the third nova package I report the same issue. Maybe the problem with Packagist??

**Comment by m2de** [comment]
Ah that would be great from my point of view ha. Thanks for the update.
