### ISSUE TITLE
Call to a member function contains() on null after updating nova

### ISSUE THREAD

**Issue by atmacoder** [Silvanite/novatoolpermissions#18]
`/home
/kpvrp56vtcsd
/public_html
/site.com
/vendor
/silvanite
/brandenburg
/src
/Traits
/HasRoles.php 
    /**
     * Determine if any of the assigned roles to this user
     * have a specific permission
     *
     * @param string $permission
     * @return boolean
     */
    public function hasRoleWithPermission($permission)
    {
        return $this->roles->contains(function ($role) use ($permission) {
            return $role->getPermissions->contains('permission_slug', $permission);
        });
    }
 
    /**
     * Assign a role to this user
     *
     * @param string|Role $role
     * @return boolean
     */
    public function assignRole($role)
    {
        if (is_string($role)) {
            return $this->roles()->attach(Role::where('slug', $role)->first());
        }`

**Comment by atmacoder** [comment]
sorry it is ok now)) 
just space between
`if(is_string($role)) {
        return $this->roles()->attach(Role::where('slug', $role)->first());
    }`

**Comment by pitylee** [comment]
This should fix the problem:

```
    /**
     * Determine if any of the assigned roles to this user
     * have a specific permission
     *
     * @param string $permission
     * @return boolean
     */
    public function hasRoleWithPermission($permission)
    {
        return !is_null($this->roles()->count()) ? $this->roles()->get()->contains(function ($role) use ($permission) {
            return $role->getPermissions()->get()->contains('permission_slug', $permission);
        }) : null;
    }
```
