### ISSUE TITLE
remove viewNova from default permissions

### ISSUE THREAD

**Issue by raftalks** [Silvanite/novatoolpermissions#19]
I would recommend to remove the viewNova gate definition from the package, considering the case where if every user do have access to viewNova and roles shouldn't give anyone to configure that permission.

this package is great and should only provide a default set of gate definitions relevant to the package resource and let the developers set their own gates for user resource etc.

solution:
define only the following default permissions
```
{  "viewRoles": "View Roles",
    "manageRoles": "Manage Roles",
    "assignRoles": "Assign Roles",
}
```

**Comment by m2de** [comment]
Hi. Thanks for your report. In theory you can just leave the default gate method in place to achieve what you want. The only issue then is that the View Nova permission will appear in the UI but not actually do anything. That is much easier to resolve though.
