### ISSUE TITLE
User Resource hardcoded class issue

### ISSUE THREAD

**Issue by thierry2015** [Silvanite/novatoolpermissions#2]
*As a developer, I want to be able to use the Silvanite/novatoolpermissions package without relying on the basic Nova architecture.*

Currently, in Silvanite\NovaToolPermissions\Role, the Nova User Resource class is hardcoded, which prevent the developer to change the basic architecture.

Proposed solution: use configuration file to retrieve the project-specific class

**Comment by m2de** [comment]
I believe this is now resolved after merging and publishing your PR #3 ? Thanks again for your contribution!

**Comment by thierry2015** [comment]
Just tested it through a composer installation, this feature is correctly working and can be marked as completed, thanks for accepting my PR!
