### ISSUE TITLE
User without permissions can do anything

### ISSUE THREAD

**Issue by aramirez92** [Silvanite/novatoolpermissions#22]
I've set my custom Policy but when i try access and update the resource the user do it.

<img width="582" alt="captura de pantalla 2018-11-08 a la s 13 26 50" src="https://user-images.githubusercontent.com/2057867/48225405-fb268400-e359-11e8-807e-19c3adbea3c0.png">

<img width="1418" alt="captura de pantalla 2018-11-08 a la s 13 28 05" src="https://user-images.githubusercontent.com/2057867/48225482-31640380-e35a-11e8-9755-b964a7399130.png">

**Comment by m2de** [comment]
Hi @aramirez92 . Sorry but I'm not sure what you are asking? By design, if nobody has access to a specific role, then everyone is granted access. You need to assign each permission to a Role, and that role must be assigned to a user in order to stop the "Allow all" fallback if that makes sense?

**Comment by Giactan** [comment]
By default when nobody have permission this tool will allow anyone can access this feature can help you don't lock everyone.
When you assign at least 1 user to a role it will work like a charm!

**Comment by m2de** [comment]
Hey @aramirez92 . Please could you let me know if you are happy that everything is working so I can close this issue? Many thanks.
