### ISSUE TITLE
Publish Ressources

### ISSUE THREAD

**Issue by StanBarrows** [Silvanite/novatoolpermissions#24]
Is there any proper way to publish & override the following resource to the project by default?

- [ ] Nova Role Ressource
- [ ] RolePolicies
- [ ] UserPolicies

Cheers,
Stan

**Comment by m2de** [comment]
Hey @StanBarrows.

1. Nova Role Resource – Not currently, but it should be pretty straight forward to add this functionality, however it then adds some additional complications in that I imagine you would also want to extend the Role model?
2. Policies. I believe if you load your own Policies for the models it will replace the existing ones, however I'm not 100% sure on this. Wouldn't take much to make these configurable if it doesn't work though.

Cheers.

**Comment by StanBarrows** [comment]
Hi m2de

First of all thanks for the reply. 

I'll let you know if I've tested everything out.
