### ISSUE TITLE
Custom Policies Issue

### ISSUE THREAD

**Issue by otrsw** [Silvanite/novatoolpermissions#27]
Fristly -thanx for a really nice package!  I hope my problems are simply teething issues since I much prefer this approach to ACL over others.

Using Laravel 5.7, Nova 1.1.7
I followed the setup process all works great.  I then used your Blog example to add a policy for each of the resource models I want to protect.  Show up in UI fine and I then assigned ALL to the "super user" role:

![image](https://user-images.githubusercontent.com/15993272/50213283-d2949f80-0385-11e9-9e65-b7cedba7cb76.png)

I created new role to test somone only having access to the "Routes" (viewRoutes and manageRoutes).

However when I log in with that user I can still see all the other resources on the menu, and I can also create other resources.
The "roles" does nicely disapear as expected - but I would want my own to do the same?

![image](https://user-images.githubusercontent.com/15993272/50213422-4767d980-0386-11e9-9f36-54c112bb104d.png)

I include the relevant sections from AuthServiceProvider:

class AuthServiceProvider extends ServiceProvider
{

    use ValidatesPermissions;

    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        App\Route::class => \App\Policies\RoutePolicy::class,
        App\Order::class => \App\Policies\OrderPolicy::class,
        App\Driver::class => \App\Policies\DriverPolicy::class,
        App\Runsheet::class => \App\Policies\RunsheetPolicy::class,
        App\OrderProvider::class => \App\Policies\ConfigPolicy::class,
    ];

Boot method simply a clone and modify from your Blog sample:

    public function boot()
    {
 
        collect([
            'viewRoute',
            'manageRoute',
            'viewOrder',
            'manageOrder',
            'viewDriver',
            'manageDriver',
            'manageRunsheet',
            'viewRunsheet',
            'manageConfig',

        ])->each(function ($permission) {

            Gate::define($permission, function ($user) use ($permission) {
                if ($this->nobodyHasAccess($permission)) {
                    return true;
                }

                return $user->hasRoleWithPermission($permission);
            });
        });
 
 
        $this->registerPolicies();
    }
}

And lastlly the policy - again just a modification of Blog:

class RoutePolicy
{
    use HandlesAuthorization;

    /**
     * Create a new policy instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    public function viewAny($user)
    {
        return Gate::any(['viewRoute', 'manageRoute'], $user, $post);
    }
    
    public function view($user, $post)
    {
        return Gate::any(['viewRoute', 'manageRoute'], $user, $post);
    }
    
    public function create($user)
    {
        return $user->can('manageRoute');
    }
    
    public function update($user, $post)
    {
        return $user->can('manageRoute', $post);
    }
    
    public function delete($user, $post)
    {
        return $user->can('manageRoute', $post);
    }
    
    public function restore($user, $post)
    {
        return $user->can('manageRoute', $post);
    }
    
    public function forceDelete($user, $post)
    {
        return $user->can('manageRoute', $post);
    }

}

**Comment by otrsw** [comment]
Oh and I am testing on a remote server so its not a "local" environment issue

**Comment by m2de** [comment]
Hi @otrsw . Thanks very much. Everything looks to be correct at first glance. Please can you add a breakpoint/dump/dd inside one of the Policies which aren't working to determine that they are actually being triggered? You'll most likely need to use the inspector to view the various ajax requests to see check it.

**Comment by m2de** [comment]
Hi @otrsw . Please can you let me know if you resolved this so I can close the issue? Thanks.
