### ISSUE TITLE
BlogPolicy gives error per documentation

### ISSUE THREAD

**Issue by joeelia** [Silvanite/novatoolpermissions#28]
Your documentation states:

```
public function viewAny($user)
{
    return Gate::any(['viewBlog', 'manageBlog'], $user, $post);
}
```

but you don't pass an argument in the function of $post so it should be

```
use Illuminate\Support\Facades\Gate;

public function viewAny($user)
{
    return Gate::any(['viewBlog', 'manageBlog'], $user);
}
```

Also, you will get errors unless you import the Gate Facades.

**Comment by m2de** [comment]
Hi @joeelia 

Thanks, that is indeed an error. Will update the docs.

Cheers.
