### ISSUE TITLE
migrations for novatoolpermission

### ISSUE THREAD

**Issue by devops-drop** [Silvanite/novatoolpermissions#32]
I haven't found Migration for novatoolpermission module.

**Comment by m2de** [comment]
Hi @devops-drop . The tool uses Brandenburg to manage permissions which is where the migrations are managed. https://github.com/Silvanite/brandenburg. Hope that helps.

**Comment by m2de** [comment]
Closing this, please comment if this hasn't been resolved. Thank you.
