### ISSUE TITLE
Call to undefined method Silvanite\NovaToolPermissions\Role::singleRecord()

### ISSUE THREAD

**Issue by Dontorpedo** [Silvanite/novatoolpermissions#33]
after installation, the mentioned error appears..

**Comment by Dontorpedo** [comment]
do you need more info on this? i still cant use the package :/

as for now

Laravel 5.8.8
Nova: 2.0.1

**Comment by preliot** [comment]
perhaps:

- wrong php version
- composer dumpautoload

**Comment by Dontorpedo** [comment]
i found the answer....

looks like it is a kind of compability issue with another package:

https://github.com/daniel-de-wit/nova-single-record-resource

so i close this for now.

**Comment by m2de** [comment]
Thanks for the update @Dontorpedo .
