### ISSUE TITLE
How do I use another table/model?

### ISSUE THREAD

**Issue by luscas** [Silvanite/novatoolpermissions#35]
How do I use another model? By default, they use Users, but I'm using Admin...
Error:
![image](https://user-images.githubusercontent.com/6822485/51991743-83648300-248a-11e9-8170-fa3d19b8349c.png)

**Comment by m2de** [comment]
Hi. I'm not quite sure what you are trying to do. Please can you provide some more code to demonstrate your situation? Thank you.
