### ISSUE TITLE
Assign Role to User not showing BelongsToMany field

### ISSUE THREAD

**Issue by elijahworkz** [Silvanite/novatoolpermissions#4]
I want to add ability to assign a role to user from User details edit page and I added the field to user resource as mentioned but the field is not shown.
I was also wondering how that would work with a user possibly having multiple roles?

**Comment by m2de** [comment]
Hi @elijahworkz ... you need to look at the details page for a user in order to assign / manage roles. This is how Nova handles relationships.

**Comment by elijahworkz** [comment]
@m2de  Oops
thanks so much!!! 
now what you wrote earlier makes perfect sense. I should've picked up on this earlier, but I'm still figuring this nova thing out.
