### ISSUE TITLE
Add to a Group

### ISSUE THREAD

**Issue by ilvitous** [Silvanite/novatoolpermissions#44]
Hello is it possible to add Roles under a group for example USERS?
public static $group = "USERS";
Thank you

**Comment by tumispro** [comment]
Any plans on adding this? Looks messy currently when resources are grouped.

**Comment by m2de** [comment]
Unless I am misunderstanding you can already do this using the `roleResourceGroup` config value. https://github.com/Silvanite/novatoolpermissions/blob/4375bfa2a1612db67adb281585e5ffd02fba91fd/src-php/Configs/novatoolpermissions.php#L13

Please let me know if this isn't what you were trying to do and I can re-open the issue. Cheers.

**Comment by tumispro** [comment]
Excellent, sorry I missed that. Thank you!
