### ISSUE TITLE
Slug field not functioning

### ISSUE THREAD

**Issue by akmalelias** [Silvanite/novatoolpermissions#45]
I noticed after new update of benjaminhirsch/nova-slug-field, slug field in this package also affected. According to the update notice of that package:
"If you are updating to a version equal or higher then 1.2.1, then you should be aware, that the slug is now using the attribute instead of the name. In case you have ->slug('Slug'), the parameter hast to be lower case or equal the column_name."

So need to update this package as well. Thanks

**Comment by m2de** [comment]
Thanks for the info @akmalelias . Have released an update to resolve this. Please let me know if you still have issues.
