### ISSUE TITLE
Role in metirc

### ISSUE THREAD

**Issue by Ji20on** [Silvanite/novatoolpermissions#48]
how can i count data from Role model into my metric? I mean, I want to show in metric if how many admins, users. in my database users

**Comment by Ji20on** [comment]
![Capture](https://user-images.githubusercontent.com/29293778/60146582-b2dea800-97fc-11e9-841f-c58d871b0d85.PNG)

**Comment by m2de** [comment]
You should be able to access the Role model like any other to get the data you need. It has a `users()` relationship which you can use to count the number of users on each model. E.g. `Role::first()->users()->count()` Please let me know if you need any more info. Cheers.

**Comment by abordage** [comment]
```php
public function calculate(Request $request)
{
    $result = Role::withCount([
        'users' => static function (Builder $query) {
            $query->whereNull('banned_at');
        },
    ])
        ->orderBy('users_count', 'desc')
        ->get()
        ->mapWithKeys(static function ($item) {
            return [$item['name'] => $item['users_count']];
        })
        ->put('Banned', User::whereNotNull('banned_at')->count())
        ->toArray();

    return $this->result($result);
}
```
