### ISSUE TITLE
Role creation does not work when User model is in different folder/namespace

### ISSUE THREAD

**Issue by lesaff** [Silvanite/novatoolpermissions#5]
I have all my `Models` stored in `App/Models` folder. I've also set my `$model` accordingly
```
public static $model = 'App\\Models\\User';
```

But whenever I tried to create a new role, it threw an exception below

```
Class 'App\User' not found
/Users/####/####/portal/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasRelationships.php#656
Symfony\Component\Debug\Exception\FatalThrowableError
     */
    protected function newRelatedInstance($class)
    {
        return tap(new $class, function ($instance) {
            if (! $instance->getConnectionName()) {
                $instance->setConnection($this->connection);
            }
```

**Comment by m2de** [comment]
I believe this is a duplicate of #2 which is already in PR. Will leave open for reference though until resolved.

**Comment by m2de** [comment]
Ah, my bad, I mis-read the original post. Thanks @thierry2015 , that is correct, you can edit this in your brandenburg config (and there are plans to replace this for the default Laravel configuration value in the next major release). Thanks for you input.

**Comment by lesaff** [comment]
@thierry2015 That did it. Thanks for your help!
