### ISSUE TITLE
ability to customize Nova availableForNavigation function 

### ISSUE THREAD

**Issue by nchornii** [Silvanite/novatoolpermissions#57]
For now, the `Roles` menu is displaying for everyone. Need ability to create custom `availableForNavigation` function to display only for admins

**Comment by m2de** [comment]
It shouldn't be displayed unless a user has `viewRoles` permission. Also, if no user is assigned `viewRoles` then all users will see it.

**Comment by nchornii** [comment]
@m2de that works, thanks
