### ISSUE TITLE
Class "App\User" not found after creating a role

### ISSUE THREAD

**Issue by safeboot** [Silvanite/novatoolpermissions#66]
I did have another error but that was cleaned with updating composer and publishing Nova. Now I can't access Nova because the error "Class "App\User" not found" is blocking my way after I log into Nova.

What can I do? I am using Laravel 8 which puts the User model in app\models.

**Comment by sigaev-pro** [comment]
Hello, have the same problem with Laravel 8. Did you solved the problem?

**Comment by fredroo** [comment]
My app have a name then App is not more the path right, @sigaev-pro your project have a name for App in env file
