### ISSUE TITLE
Error: Call to undefined method Silvanite\Brandenburg\Role::uriKey()

### ISSUE THREAD

**Issue by tobz-nz** [Silvanite/novatoolpermissions#8]
I'm getting the error `Call to undefined method Silvanite\Brandenburg\Role::uriKey()` on the user resource page - for the call to `/nova-api/users?search=&filters=&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=&viaResourceId=&viaRelationship=&relationshipType=`.

Breaks the page.

**Comment by tobz-nz** [comment]
Aha, I had imported the wrong `Role` class for the user fields.

**Comment by m2de** [comment]
No worries, glad you’re up and running!

**Comment by Ji20on** [comment]
how can i call data from Role model into my metric? I mean, I want to show in metric if how many admins, users.
