### ISSUE TITLE
How people can edit their profile

### ISSUE THREAD

**Issue by tolawho** [Silvanite/novatoolpermissions#9]
I have 2 user types: admin and buyer, only admin can see the Users resource and have full permission(viewUsers, manageUsers). The buyer can't see the Users resource because buyer dont have (viewUsers, manageUsers), but I want the buyer can update  their profile, I make a menu like image below, and the link of profile is http://*****.****/nova/resources/users/3  // 3 is their user id

![image](https://user-images.githubusercontent.com/12527881/45534985-188e1480-b827-11e8-80c7-809b2aba3762.png)

Please help How to I can do it.

Sorry for my english. Thanks

**Comment by m2de** [comment]
Hi @tolawho ... if I understand correctly, you would need to register your own User Policy to overwrite the package defaults and add a permissions to see if the user is allowed to view that specific resource (refer to Laravel Documentation on this)

**Comment by m2de** [comment]
Hi @tolawho . Please can you let me know if you still need anything or if I can close this issue? Many thanks!

**Comment by tolawho** [comment]
Thank you for your comment, i will close it.
